services:
  db:
    image: postgres:16-alpine
    container_name: todo-db
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5up3r53cr3t
    ports:
      - "5432:5432"

  backend:
    build: .
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    command: >
      sh -c "for i in 1 2 3 4 5; do alembic upgrade head && break || sleep 2; done &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000"

